Ubuntu Compatibility  (#1)
* initial commit

* General reformatting to make it look pretty

* Molecule Tests (#3)

* change include_tasks to just include

* Move installation of dependencies into own file

* Break the configuration into its own file

* Moves the zip install to install-prereqs

* Turns the zip location into a variable

* Encapsulate variables for configure task

* Make things look nicer

* Adds molecule tests

* Fix yamllint problems

* Fix flake8 lint

* Fix ansible lint problems

* removes pyc

* Fix tests

* Removes travis for internal circle (#4)

diff --git a/templates/cw-put-instance-data.sh.j2 b/templates/cw-put-instance-data.sh.j2
--- a/templates/cw-put-instance-data.sh.j2
+++ b/templates/cw-put-instance-data.sh.j2
@@ -7,4 +7,4 @@ if [ ! -d $AWS_EC2CW_META_DATA ]; then
     mkdir -p $AWS_EC2CW_META_DATA
 fi
 
-{{cw_install_dir}}/mon-put-instance-data.pl {{cw_options}} --from-cron || logger -t aws-scripts-mon "status=failed exit_code=$?"
+{{ cw_install_dir }}/mon-put-instance-data.pl {{ cw_options }} --from-cron || logger -t aws-scripts-mon "status=failed exit_code=$?"
